micronaut:
  application:
    name: {{ cookiecutter.__example }}
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: postgres
    password: postgres123
netty:
  default:
    allocator:
      max-order: 3
r2dbc:
  datasources:
    default:
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: postgres
      password: postgres123
